version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/editor-server/secrets
    environment:
      - ROCKET_SECRET_KEY=${ROCKET_SECRET_KEY}
      - ROCKET_DATABASES={hci_bildung={url="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"}}
  db:
    image: postgres:latest
    volumes:
      - ./db_scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  dbdata:
