version: "3.9"

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DB_POOL_SIZE=20
      - ROCKET_SECRET_KEY=${ROCKET_SECRET_KEY}
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    build:
      context: .
      dockerfile: deployment/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CERT_PATH}:/secrets

volumes:
  dbdata:
