name: Build Status

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install native dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y libpq-dev
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: vue/package-lock.json
      - name: Install Node dependencies
        working-directory: ./vue
        run: npm install
      - name: Build frontend
        working-directory: ./vue
        run: npm run build
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: Build backend
        run: cargo build
